import {
  DashboardStats,
  Job,
  Candidate,
  Application,
  Course,
  Enrollment,
  ActivityItem,
} from "@/types/schema";

export const dashboardStats: DashboardStats = {
  total_candidates: 12480,
  total_candidates_change: 8.2,
  active_jobs: 347,
  active_jobs_new_today: 12,
  placements_made: 2190,
  placements_change: 5.4,
  revenue: 184500,
  revenue_change: 11,
};

export const registrationsVsPlacements = [
  { month: "Apr", registrations: 820, placements: 140 },
  { month: "May", registrations: 950, placements: 175 },
  { month: "Jun", registrations: 880, placements: 160 },
  { month: "Jul", registrations: 1100, placements: 210 },
  { month: "Aug", registrations: 1240, placements: 235 },
  { month: "Sep", registrations: 1080, placements: 195 },
  { month: "Oct", registrations: 1350, placements: 260 },
  { month: "Nov", registrations: 1420, placements: 280 },
  { month: "Dec", registrations: 1200, placements: 240 },
  { month: "Jan", registrations: 1550, placements: 310 },
  { month: "Feb", registrations: 1680, placements: 340 },
  { month: "Mar", registrations: 1820, placements: 375 },
];

export const jobCategories = [
  { name: "Frontend", value: 28, color: "#1C7272" },
  { name: "Backend", value: 22, color: "#F5A623" },
  { name: "DevOps", value: 12, color: "#22A87A" },
  { name: "Design", value: 15, color: "#3B9EE0" },
  { name: "Data", value: 13, color: "#E84545" },
  { name: "Mobile", value: 10, color: "#9B59B6" },
];

export const topJobCategories = [
  { name: "Frontend Development", placements: 485 },
  { name: "Backend Engineering", placements: 412 },
  { name: "Product Design", placements: 298 },
  { name: "Data Science", placements: 267 },
  { name: "DevOps / Cloud", placements: 218 },
  { name: "Mobile Development", placements: 190 },
];

export const recentApplications: Application[] = [
  {
    id: "app-001",
    candidate_name: "Sarah Kolade",
    candidate_avatar: null,
    candidate_email: "sarah.k@email.com",
    job_title: "Senior React Developer",
    company: "Paystack",
    status: "shortlisted",
    applied_date: "2024-03-08",
  },
  {
    id: "app-002",
    candidate_name: "Emeka Obi",
    candidate_avatar: null,
    candidate_email: "emeka.o@email.com",
    job_title: "DevOps Engineer",
    company: "Flutterwave",
    status: "applied",
    applied_date: "2024-03-08",
  },
  {
    id: "app-003",
    candidate_name: "Amara Diallo",
    candidate_avatar: null,
    candidate_email: "amara.d@email.com",
    job_title: "Product Designer",
    company: "Andela",
    status: "hired",
    applied_date: "2024-03-07",
  },
  {
    id: "app-004",
    candidate_name: "Tunde Adeyemi",
    candidate_avatar: null,
    candidate_email: "tunde.a@email.com",
    job_title: "Data Engineer",
    company: "Kuda Bank",
    status: "rejected",
    applied_date: "2024-03-07",
  },
  {
    id: "app-005",
    candidate_name: "Ify Nwosu",
    candidate_avatar: null,
    candidate_email: "ify.n@email.com",
    job_title: "Backend Engineer",
    company: "Moniepoint",
    status: "shortlisted",
    applied_date: "2024-03-06",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "act-001",
    actor_name: "Sarah Kolade",
    actor_avatar: null,
    action: "applied for Senior React Developer at Paystack",
    timestamp: "2m ago",
  },
  {
    id: "act-002",
    actor_name: "Emeka Obi",
    actor_avatar: null,
    action: "completed DevOps Fundamentals course",
    timestamp: "15m ago",
  },
  {
    id: "act-003",
    actor_name: "Admin",
    actor_avatar: null,
    action: "posted a new job: Product Designer at Andela",
    timestamp: "42m ago",
  },
  {
    id: "act-004",
    actor_name: "Amara Diallo",
    actor_avatar: null,
    action: "was hired as Product Designer at Andela",
    timestamp: "1h ago",
  },
  {
    id: "act-005",
    actor_name: "Chibuzor Eze",
    actor_avatar: null,
    action: "registered as a new talent",
    timestamp: "2h ago",
  },
  {
    id: "act-006",
    actor_name: "Fatima Bello",
    actor_avatar: null,
    action: "enrolled in Full-Stack Web Development Bootcamp",
    timestamp: "3h ago",
  },
];

export const upcomingEvents = [
  {
    id: "evt-001",
    title: "Tech Career Bootcamp — Lagos",
    date: "Mar 15, 2024",
    type: "In-person",
    registered: 120,
  },
  {
    id: "evt-002",
    title: "Remote Work Masterclass",
    date: "Mar 20, 2024",
    type: "Virtual",
    registered: 340,
  },
  {
    id: "evt-003",
    title: "React & Next.js Advanced Training",
    date: "Mar 25, 2024",
    type: "Virtual",
    registered: 185,
  },
  {
    id: "evt-004",
    title: "Tech Talent Showcase — Abuja",
    date: "Apr 2, 2024",
    type: "In-person",
    registered: 75,
  },
];

export const mockJobs: Job[] = [
  {
    id: "job-001",
    title: "Senior React Developer",
    company: "Paystack",
    type: "Remote",
    category: "Frontend",
    applicants_count: 48,
    status: "active",
    posted_date: "2024-03-01",
    description: "Build and maintain scalable React applications for Africa's leading payments company.",
    location: "Lagos, Nigeria",
    salary_range: "$60k–$90k",
  },
  {
    id: "job-002",
    title: "DevOps Engineer",
    company: "Flutterwave",
    type: "Hybrid",
    category: "DevOps",
    applicants_count: 23,
    status: "active",
    posted_date: "2024-03-03",
    description: "Manage infrastructure, CI/CD pipelines, and cloud deployments.",
    location: "San Francisco, CA",
    salary_range: "$80k–$120k",
  },
  {
    id: "job-003",
    title: "Product Designer",
    company: "Andela",
    type: "Remote",
    category: "Design",
    applicants_count: 67,
    status: "active",
    posted_date: "2024-03-05",
    description: "Design intuitive interfaces for enterprise software solutions.",
    location: "Remote",
    salary_range: "$50k–$75k",
  },
  {
    id: "job-004",
    title: "Data Engineer",
    company: "Kuda Bank",
    type: "Onsite",
    category: "Data",
    applicants_count: 31,
    status: "active",
    posted_date: "2024-03-06",
    description: "Build data pipelines and analytics infrastructure.",
    location: "Lagos, Nigeria",
    salary_range: "$55k–$80k",
  },
  {
    id: "job-005",
    title: "Backend Engineer (Node.js)",
    company: "Moniepoint",
    type: "Remote",
    category: "Backend",
    applicants_count: 54,
    status: "active",
    posted_date: "2024-03-07",
    description: "Build high-performance APIs for Nigeria's fastest-growing fintech.",
    location: "Remote",
    salary_range: "$65k–$95k",
  },
  {
    id: "job-006",
    title: "iOS Developer",
    company: "PiggyVest",
    type: "Hybrid",
    category: "Mobile",
    applicants_count: 19,
    status: "closed",
    posted_date: "2024-02-20",
    description: "Develop native iOS applications for personal finance.",
    location: "Lagos, Nigeria",
    salary_range: "$55k–$80k",
  },
  {
    id: "job-007",
    title: "Machine Learning Engineer",
    company: "Terragon Group",
    type: "Remote",
    category: "Data",
    applicants_count: 0,
    status: "draft",
    posted_date: "2024-03-08",
    description: "Build ML models for audience segmentation and targeting.",
    location: "Remote",
    salary_range: "$70k–$100k",
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: "cand-001",
    name: "Sarah Kolade",
    email: "sarah.k@email.com",
    avatar: null,
    skills: ["React", "TypeScript", "GraphQL"],
    location: "Lagos, Nigeria",
    status: "active",
    applied_jobs: 3,
    experience_years: 5,
    created_at: "2024-01-15",
  },
  {
    id: "cand-002",
    name: "Emeka Obi",
    email: "emeka.o@email.com",
    avatar: null,
    skills: ["AWS", "Docker", "Kubernetes"],
    location: "Abuja, Nigeria",
    status: "active",
    applied_jobs: 2,
    experience_years: 4,
    created_at: "2024-01-20",
  },
  {
    id: "cand-003",
    name: "Amara Diallo",
    email: "amara.d@email.com",
    avatar: null,
    skills: ["Figma", "Product Design", "Prototyping"],
    location: "Accra, Ghana",
    status: "hired",
    applied_jobs: 5,
    experience_years: 3,
    created_at: "2023-12-10",
  },
  {
    id: "cand-004",
    name: "Tunde Adeyemi",
    email: "tunde.a@email.com",
    avatar: null,
    skills: ["Python", "Spark", "SQL"],
    location: "Ibadan, Nigeria",
    status: "active",
    applied_jobs: 1,
    experience_years: 6,
    created_at: "2024-02-01",
  },
  {
    id: "cand-005",
    name: "Ify Nwosu",
    email: "ify.n@email.com",
    avatar: null,
    skills: ["Node.js", "PostgreSQL", "Redis"],
    location: "Port Harcourt, Nigeria",
    status: "active",
    applied_jobs: 4,
    experience_years: 7,
    created_at: "2023-11-05",
  },
  {
    id: "cand-006",
    name: "Chibuzor Eze",
    email: "chibu.e@email.com",
    avatar: null,
    skills: ["React Native", "iOS", "Android"],
    location: "Enugu, Nigeria",
    status: "active",
    applied_jobs: 2,
    experience_years: 4,
    created_at: "2024-02-18",
  },
  {
    id: "cand-007",
    name: "Fatima Bello",
    email: "fatima.b@email.com",
    avatar: null,
    skills: ["Vue.js", "Nuxt", "CSS"],
    location: "Kano, Nigeria",
    status: "inactive",
    applied_jobs: 0,
    experience_years: 2,
    created_at: "2024-03-01",
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-001",
    title: "Full-Stack Web Development Bootcamp",
    thumbnail: null,
    instructor: "David Okafor",
    enrolled_count: 312,
    progress: 68,
    status: "published",
    category: "Web Development",
    duration: "12 weeks",
  },
  {
    id: "course-002",
    title: "React & Next.js Advanced Patterns",
    thumbnail: null,
    instructor: "Grace Mensah",
    enrolled_count: 187,
    progress: 45,
    status: "published",
    category: "Frontend",
    duration: "8 weeks",
  },
  {
    id: "course-003",
    title: "Cloud Infrastructure with AWS",
    thumbnail: null,
    instructor: "Kunle Adewale",
    enrolled_count: 94,
    progress: 30,
    status: "published",
    category: "DevOps",
    duration: "10 weeks",
  },
  {
    id: "course-004",
    title: "Product Design Fundamentals",
    thumbnail: null,
    instructor: "Ngozi Eze",
    enrolled_count: 256,
    progress: 82,
    status: "published",
    category: "Design",
    duration: "6 weeks",
  },
  {
    id: "course-005",
    title: "Data Science with Python",
    thumbnail: null,
    instructor: "Yemi Sule",
    enrolled_count: 0,
    progress: 0,
    status: "draft",
    category: "Data",
    duration: "14 weeks",
  },
  {
    id: "course-006",
    title: "Mobile Development with React Native",
    thumbnail: null,
    instructor: "Bayo Adeyemi",
    enrolled_count: 0,
    progress: 0,
    status: "coming_soon",
    category: "Mobile",
    duration: "10 weeks",
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: "enr-001",
    student_name: "Sarah Kolade",
    student_avatar: null,
    course_title: "React & Next.js Advanced Patterns",
    progress: 78,
    completion_date: null,
    certificate_issued: false,
  },
  {
    id: "enr-002",
    student_name: "Emeka Obi",
    student_avatar: null,
    course_title: "Cloud Infrastructure with AWS",
    progress: 100,
    completion_date: "2024-02-28",
    certificate_issued: true,
  },
  {
    id: "enr-003",
    student_name: "Fatima Bello",
    student_avatar: null,
    course_title: "Full-Stack Web Development Bootcamp",
    progress: 42,
    completion_date: null,
    certificate_issued: false,
  },
  {
    id: "enr-004",
    student_name: "Tunde Adeyemi",
    student_avatar: null,
    course_title: "Data Science with Python",
    progress: 100,
    completion_date: "2024-03-01",
    certificate_issued: true,
  },
];
